name: Create and publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build
        env:
          TERRGRUNT_VERSION: ${{vars.TERRGRUNT_VERSION}}
          DOCKER_USER: ${{secrets.DOCKER_USER}}
        run: docker build --build-arg version=$TERRAGRUNT_VERSION . --file ci/files/Dockerfile --tag $DOCKER_USER/selfhosted-runner:latest

      - name: Push
        run: docker push ${{secrets.DOCKER_USER}}/selfhosted-runner:latest
